### ISSUE TITLE
request/reply problems

### ISSUE THREAD

**Issue by WallStProg** [fquinner/OpenMAMA-zmq#16]
I've been spending some time working on request/reply with the 0mq bridge, and working through some problems.  Based on that, I *think* the current approach is unworkable, but I'm curious to know if you agree, and if so, whether you have any thoughts on how to make it work.

The main problem appears to be that each inbox is associated with a unique topic name, which the inbox subscribes to in order to receive replies.

Most of the time that works, but since filtering in 0mq is (usually) done on the publisher, and since there is a window between the time that a subscription is created and when it is known by the publisher, occassionally replies just "go missing" -- the zmq_send call (zmqBridgeMamaPublisher_sendReplyToInboxHandle => zmqBridgeMamaPublisher_send) on the "server" succeeds, but the reply message is never put on the wire.  (I was able to confirm this using the very handy [zmtpdump](https://github.com/zeromq/zmtpdump) program, and interpolating its output with enhanced logs from both the client and server test programs).

That also explains why I see the problem with TCP and IPC connections, but not with EPGM, since with EPGM filtering is done on the subscriber, rather than on the publisher.

So, I'm wondering if you have any thoughts on how best to deal with this?  Off the top of my head, it seems like some kind of two-level subscription might work -- that is, where the subscriber subscribes to a broad topic (e.g., "_INBOX.{machine_name}.{process_id}") and then further filters incoming messages based on some additional fields in the message.

One nice thing about that approach is it could also be used to implement wildcard subscriptions, which are currently not supported at all with the 0mq bridge. 

If you have time to give this some thought, I'd be very interested in any suggestions you might have. Thanks!

**Comment by fquinner** [comment]
Yeah unfortunately issues like this are a known issue with zmq since the publisher doesn't care if people are subscriber or not when it drops messages on send. I'd like to see what you're seeing first though to see if there are any options and if I can fully understand if this is just a slow joiner issue or something else. Ideally we could just leave it the way it is and tweak our way out of it.

How are you recreating this atm?

The reply topic looks like it's generated for each inbox. If needs be, it should probably be distinct per client rather than per inbox and created on transport initialization. Further filtering can be done in meta data.

**Comment by WallStProg** [comment]
Here's a sample.  I added logging in 0mq bridge, and modified both OpenMama and zmtpdump to output timestamps in micros.

[sample.numbers.pdf](https://github.com/fquinner/OpenMAMA-zmq/files/1072930/sample.numbers.pdf)
