### ISSUE TITLE
mamaIO_* functions?

### ISSUE THREAD

**Issue by WallStProg** [fquinner/OpenMAMA-zmq#20]
HI Frank:

I notice that you provide what looks like a complete implementation of the mamaIO_* functions in the zmq bridge, although it's not at all clear to me what those functions do, or what one would use them for.  

I also notice that those functions appear to be completely unused.

Are these vestigial appendages that exist merely to allow the bridge to pass the Mama unit tests?  Or do they serve some purpose that I'm not seeing?

Thanks!

Bill

**Comment by fquinner** [comment]
Hi Bill,

Yes this was always a bit of a grey area for me. It's effectively a pass-through public API (https://openmama.github.io/reference/mama/c/io_8h.html) so we can't really touch it in OpenMAMA 6 but i'm keen to take it out in OpenMAMA 7 since there are many libraries out there that will do a better job than OpenMAMA at solving that problem.

The only example app that actually uses it (ignoring the unit tests for now) is https://github.com/OpenMAMA/OpenMAMA/blob/master/mamda/c_cpp/src/examples/orderbooks/bookviewer.cpp which unfortunately depends on IO behaving in a quite specific way so it's not even a properly generic API for I/O (it depends on getting a callback on IO change rather than allowing wait for flush on newline for keypresses).

But yes because that example application uses it, I wrote an implementation for it in zmq and qpid (which eventually i'm hoping to collapse, see: https://github.com/OpenMAMA/OpenMAMA/issues/322), and I didn't remove the existing unit tests (as much as I wanted to).

Within internal MAMA though (unlike timers and queues), it's literally not mandated anywhere.

Cheers,
Frank

**Comment by WallStProg** [comment]
Thanks Frank.

So, it's still not clear to me, but from your comments it sounds like the mamaIo* functions are intended for console (screen/keyboard) I/O? 

If that's the case I would tend to agree that they really don't belong in OpenMAMA ;-)

**Comment by fquinner** [comment]
They're actually for I/O for any file descriptor - bookviewer just happens to use 0 for keyboard capture. Technically you could use for any descriptor but as you said I really don't think that belongs in OpenMAMA and I struggle to find a single use case where it would be useful.
